### ISSUE TITLE
[BUG] Error: "Cannot find module ..." on startup

### ISSUE THREAD

**Issue by SashoStoichkov** [nhcarrigan/nhcarrigan-npm#5]
# Bug Report

## Describe the bug

On startup `nhcarrigan` throws an error regarding missing module `../prod/index.js` 

## Screenshots

![image](https://user-images.githubusercontent.com/24972335/110022346-7b93fe80-7d34-11eb-81a6-dcac5973e5fa.png)

**Comment by nhcarrigan** [comment]
I am unable to reproduce this on my end. Could you provide the steps you took that led to this error?

**Comment by SashoStoichkov** [comment]
![image](https://user-images.githubusercontent.com/24972335/110026444-4fc74780-7d39-11eb-99d8-591baff049b9.png)

**Comment by SashoStoichkov** [comment]
Ohhh I see the problem now - I don't have the latest node

**Comment by SashoStoichkov** [comment]
Apparently my version is up-to-date (Manjaro)
![image](https://user-images.githubusercontent.com/24972335/110026826-dc720580-7d39-11eb-9c83-27e88f0c2609.png)

**Comment by nhcarrigan** [comment]
I believe I found the issue. Could you run the install command again and try the CLI call?

**Comment by SashoStoichkov** [comment]
Okay - now it works 👍🏻

![image](https://user-images.githubusercontent.com/24972335/110027819-214a6c00-7d3b-11eb-8930-28425e325d63.png)

**Comment by nhcarrigan** [comment]
When I updated the dependencies and moved to npm 7, I republished. But I forgot to build, first, so the actual package files weren't in the publish. 🤣
