### ISSUE TITLE
[DOC] - Add Set up Instructions

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/nhcarrigan-npm#8]
# Incorrect Documentation

## Describe the error

The CONTRIBUTING.md file currently lacks specific setup instructions.

## Expected information

We need to add the following information to the `Setting Up Your Code` section:
- Installing dependencies (`npm ci`)
- Building files (`npm run build`)
- Running linter (`npm run lint`)
- Validating tests (`npm run test`)
- Generating `npm` test package (`npm pack`)
- Installing test package (`npm i -g <tgz file>`)

**Comment by bishalr0y** [comment]
Hello, I'm interested to work on this issue. Can you tell me where should I add this section?

**Comment by nhcarrigan** [comment]
The information should be added underneath the existing text of the `Setting Up Your Code` section in [CONTRIBUTING.md](../blob/main/CONTRIBUTING.md).

You can see an example of the text to add [on one of my other projects](https://github.com/nhcarrigan/gimme-colours/blob/main/CONTRIBUTING.md)

**Comment by bishalr0y** [comment]
Thanks for the information
